events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log warn;

  upstream active_app {
    include /etc/nginx/conf.d/active-upstream.conf;
  }

  server {
    listen 80;

    location /health {
      proxy_pass http://active_app/health;
    }

    location / {
      proxy_pass http://active_app;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
